{% set name = "inept" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inept-{{ version }}.tar.gz
  sha256: de89a31d8111a6165117d36d71eaefcffc5ddcfad56a42daabeac0daec24679f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
    - wheel
  run:
    - click
    - python >=3.6

test:
  imports:
    - inept
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/brgm/inept
  summary: INteractive Editable oPTions
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fsmaibrgm
